package vn.youtubemusic.audio;

import org.bukkit.Bukkit;
import org.bukkit.SoundCategory;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerResourcePackStatusEvent;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;
import vn.youtubemusic.music.MusicManager;
import vn.youtubemusic.music.Track;
import java.nio.file.Path;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import org.bukkit.scheduler.BukkitTask;

/** Delivers generated Java resource packs and starts audio only after the client is ready. */
public final class JavaAudioDelivery implements Listener {
    private final JavaPlugin plugin; private final MusicManager music; private final ResourcePackServer server;
    private final Map<UUID, Pending> pending = new ConcurrentHashMap<>(); private final Map<String, String> soundKeys = new ConcurrentHashMap<>(); private final Map<String, TrackState> states = new ConcurrentHashMap<>(); private final Map<UUID, BukkitTask> timeouts = new ConcurrentHashMap<>();
    public JavaAudioDelivery(JavaPlugin plugin, MusicManager music) {
        this.plugin=plugin; this.music=music; Path root=plugin.getDataFolder().toPath().resolve("resource-packs"); int port=plugin.getConfig().getInt("audio.resource-pack-server-port",8126); this.server=new ResourcePackServer(root,port); plugin.getServer().getPluginManager().registerEvents(this,plugin);
        if(plugin.getConfig().getBoolean("audio.resource-pack-server.enabled",true)){try{server.start();plugin.getLogger().info("Resource-pack server đang nghe cổng "+port);}catch(Exception e){plugin.getLogger().warning("Không thể mở resource-pack server: "+e.getMessage());}}
    }
    public void prepareAndPlay(AudioBackend.ResolvedAudio resolved){plugin.getServer().getScheduler().runTaskAsynchronously(plugin,()->{try{String sound="track_"+resolved.track().id().replaceAll("[^A-Za-z0-9_]","_");ResourcePackBuilder.Pack pack=ResourcePackBuilder.build(resolved.audioFile(),plugin.getDataFolder().toPath().resolve("resource-packs"),"youtubemusic:"+sound,"YouTubeMusic - "+resolved.track().title());soundKeys.put(resolved.track().id(),"youtubemusic:"+sound);String template=plugin.getConfig().getString("audio.resource-pack-url-template","");if(template.isBlank())throw new IllegalStateException("audio.resource-pack-url-template chưa được cấu hình.");String url=String.format(template,pack.zip().getFileName().toString());Bukkit.getScheduler().runTask(plugin,()->deliver(resolved.track(),url,pack.sha1(),soundKeys.get(resolved.track().id())));}catch(Exception e){plugin.getLogger().warning("Audio backend lỗi: "+e.getMessage());Bukkit.getScheduler().runTask(plugin,()->music.audioFailed(resolved.track(),e.getMessage()));}});}
    private void deliver(Track track,String url,byte[] hash,String soundKey){if(hash==null||hash.length!=20){music.audioFailed(track,"SHA-1 resource pack phải có đúng 20 byte.");return;}TrackState trackState=new TrackState();trackState.url=url;trackState.hash=hash.clone();trackState.soundKey=soundKey;states.put(track.id(),trackState);boolean force=plugin.getConfig().getBoolean("audio.resource-pack-required",false);int players=0;for(Player p:Bukkit.getOnlinePlayers()){if(music.current()==null||!music.current().id().equals(track.id()))return;players++;try{BukkitTask old= timeouts.remove(p.getUniqueId());if(old!=null)old.cancel();UUID requestId=UUID.randomUUID();pending.put(p.getUniqueId(),new Pending(requestId,track,soundKey));scheduleTimeout(p.getUniqueId(),requestId,track);p.addResourcePack(requestId,url,hash,"YouTube Music cần tải gói âm thanh để phát nhạc.",force);}catch(Exception e){plugin.getLogger().warning("Không gửi được resource pack cho "+p.getName()+": "+e.getMessage());}}if(players==0)music.audioFailed(track,"Không có người chơi Java để phát âm thanh.");}
    private void scheduleTimeout(UUID playerId,UUID requestId,Track track){int seconds=Math.max(10,plugin.getConfig().getInt("audio.resource-pack-timeout-seconds",90));BukkitTask task=Bukkit.getScheduler().runTaskLater(plugin,()->{Pending p=pending.get(playerId);if(p!=null&&p.requestId().equals(requestId)&&p.track().id().equals(track.id())){pending.remove(playerId,p);Player player=Bukkit.getPlayer(playerId);if(player!=null)pSendError(player,"TIMEOUT");if(pending.values().stream().noneMatch(x->x.track().id().equals(track.id()))){TrackState state=states.get(track.id());if(state==null||!state.success.get())music.audioFailed(track,"Hết thời gian chờ tải resource pack.");}}},seconds*20L);timeouts.put(playerId,task);}
    @EventHandler public void onPackStatus(PlayerResourcePackStatusEvent event){Pending value=pending.get(event.getPlayer().getUniqueId());if(value==null||music.current()==null||!music.current().id().equals(value.track().id())||!value.requestId().equals(event.getID()))return;if(event.getStatus()==PlayerResourcePackStatusEvent.Status.SUCCESSFULLY_LOADED){pending.remove(event.getPlayer().getUniqueId());BukkitTask timeout=timeouts.remove(event.getPlayer().getUniqueId());if(timeout!=null)timeout.cancel();TrackState state=states.computeIfAbsent(value.track().id(),k->new TrackState());Player p=event.getPlayer();float volume=music.volume(p)/100f;if(volume>0)p.playSound(p.getLocation(),value.soundKey(),SoundCategory.MASTER,volume,1f);if(state.success.compareAndSet(false,true))music.audioPlaybackStarted(value.track());}else if(event.getStatus()==PlayerResourcePackStatusEvent.Status.DECLINED||event.getStatus()==PlayerResourcePackStatusEvent.Status.FAILED_DOWNLOAD||event.getStatus()==PlayerResourcePackStatusEvent.Status.INVALID_URL){pending.remove(event.getPlayer().getUniqueId());BukkitTask timeout=timeouts.remove(event.getPlayer().getUniqueId());if(timeout!=null)timeout.cancel();pSendError(event.getPlayer(),event.getStatus().name());if(pending.values().stream().noneMatch(x->x.track().id().equals(value.track().id()))){TrackState state=states.get(value.track().id());if(state==null||!state.success.get()){states.remove(value.track().id());music.audioFailed(value.track(),"Không có người chơi nào tải được resource pack âm thanh.");}}}}
    public void updatePlayerVolume(Player player,int volume){Track current=music.current();if(current==null||player==null||!player.isOnline())return;TrackState state=states.get(current.id());if(state==null||!state.success.get()||state.soundKey==null)return;player.stopSound(state.soundKey,SoundCategory.MASTER);float level=Math.max(0,Math.min(100,volume))/100f;if(level>0)player.playSound(player.getLocation(),state.soundKey,SoundCategory.MASTER,level,1f);}
    private void pSendError(Player p,String status){p.sendMessage("§c✖ Không thể tải gói âm thanh YouTube ("+status+").");}
    @EventHandler public void onJoin(PlayerJoinEvent event){Track current=music.current();TrackState state=current==null?null:states.get(current.id());if(state==null||current==null||state.url==null||state.soundKey==null||!state.success.get())return;try{UUID requestId=UUID.randomUUID();UUID playerId=event.getPlayer().getUniqueId();BukkitTask old=timeouts.remove(playerId);if(old!=null)old.cancel();pending.put(playerId,new Pending(requestId,current,state.soundKey));scheduleTimeout(playerId,requestId,current);event.getPlayer().addResourcePack(requestId,state.url,state.hash,"YouTube Music cần tải gói âm thanh để phát nhạc.",false);}catch(Exception e){plugin.getLogger().warning("Không thể gửi resource pack cho người chơi mới: "+e.getMessage());}}
    public void stopCurrent(Track track){if(track==null)return;String key=soundKeys.get(track.id());if(key!=null)for(Player p:Bukkit.getOnlinePlayers())p.stopSound(key,SoundCategory.MASTER);for(var entry:pending.entrySet())if(entry.getValue().track().id().equals(track.id())){UUID playerId=entry.getKey();pending.remove(playerId,entry.getValue());BukkitTask timeout=timeouts.remove(playerId);if(timeout!=null)timeout.cancel();}states.remove(track.id());}
    public void shutdown(){timeouts.values().forEach(BukkitTask::cancel);timeouts.clear();pending.clear();states.clear();server.stop();}
    private static final class TrackState{private final java.util.concurrent.atomic.AtomicBoolean success=new java.util.concurrent.atomic.AtomicBoolean(false);private String url;private byte[] hash;private String soundKey;}
    private record Pending(UUID requestId,Track track,String soundKey){}
}
